// This file is generated by scripts/generate-api-contract.mjs. Do not edit manually.

export interface ApiContractApiResponse<T> {
  code: number
  message: string
  errorCode?: string
  data: T
}

export interface ApiContractPageResponse<T> {
  list: T[]
  total: number
  page: number
  pageSize: number
}

export interface ApiContractUser {
  id: number
  username: string
  avatar: string
  email?: string
  bio: string
  level: number
  experience: number
  status?: number
  createdAt: string
  hasGitHubBound?: boolean
}

export interface ApiContractPromptParams {
  temperature?: number
  topP?: number
  maxTokens?: number
  system?: string
  [key: string]: unknown
}

export interface ApiContractPrompt {
  id: number
  title: string
  description: string
  cover: string
  images: string[]
  content: string
  systemPrompt: string
  model: string
  params: ApiContractPromptParams
  categoryId: number
  categoryName: string
  tags: string[]
  userId: number
  user: ApiContractUser
  views: number
  likes: number
  favorites: number
  status: number
  createdAt: string
  updatedAt: string
}

export interface ApiContractCategory {
  id: number
  name: string
  icon: string
  count: number
}

export interface ApiContractComment {
  id: number
  targetType: "prompt" | "skill"
  targetId: number
  userId: number
  user: ApiContractUser
  content: string
  likes: number
  parentId: number | null
  replies: ApiContractComment[]
  createdAt: string
}

